services:
  app:
    build: ./app
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '5173:5173'
    command: ["sh", "-c", "yarn install && yarn dev --host"]
